---
#全局datasource配置
spring:
  datasource:                            #初始化sql配置
    initialization-mode: ALWAYS
    continue-on-error: true                        #在初始化数据库时，遇到错误是否继续，默认false
    test-on-borrow: false                           #当从连接池借用连接时，是否测试该连接.
    test-while-idle: true                           #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 3600000    #数据库连接时间


# swagger2是否开启
swagger2:
  enable: true
---
##mysql配置
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"     # mysql 8时候配置
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/taiji?serverTimezone=GMT%2B8&amp&characterEncoding=utf-8&useSSL=false
    data: "classpath:/init/mysqldata.sql"      #初始化sql配置
    schema: "classpath:/init/mysqlschema.sql"
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 3000
---
#H2配置
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /console
#  datasource:
#    url: jdbc:h2:~/tdf
#    driver-class-name: org.h2.Driver
#    data: "classpath:/init/mysqldata.sql"      #初始化sql配置
#    schema: "classpath:/init/mysqlschema.sql"
#    username: sa
#    password: sa
#oracle配置
---
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    password: 123456
#    url: jdbc:oracle:thin:@192.168.19.1:1522:ORCL1
#    username: TDFNEW
#    data: "classpath:/init/oracledata.sql"          #注意 需要将sql脚本里的用户名替换为你自己的
#    schema: "classpath:/init/oracleschema.sql"      #注意 需要将sql脚本里的用户名替换为你自己的
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://oauth2.taiji.com.cn/.well-known/jwks.json  #向OAuth2 请求密钥的接口地址
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml                           #扫描多个模块下的mapper.xml
  type-aliases-package: cn.com.tdf.log.domain,cn.com.tdf.sys.domain     #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  #type-aliases-super-type: java.lang.Object                             #该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  global-config:
    db-config:
      logic-delete-field: flag                       #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: null                      # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1                      # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #sql打印
    map-underscore-to-camel-case: true               #是否开启自动驼峰命名规则（camel case）映射,如果明明规范不需要使用@TableField
    cache-enabled: false
    call-setters-on-nulls: true
#    jdbc-type-for-null: 'null'                        #orcal需要加该配置